version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/data
      - ./app:/app
    depends_on:
      - mcp-server
    networks:
      - finance-net
    restart: unless-stopped

  mcp-server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: finance-mcp
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/data
    networks:
      - finance-net
    restart: unless-stopped

networks:
  finance-net:
    driver: bridge
